version: '3'
services:
  app:
    build: ../app
    volumes:
      - /var/run/docker.sock/:/var/run/docker.sock
      - ../app/log:/app/log
    ports:
      - 8080:8000
    depends_on:
      - db
      - pyterrier_bm25
      - pyterrier_pl2
      - pyterrier_tf

    environment:
        - RANKSYS_LIST=pyterrier_bm25 pyterrier_pl2 pyterrier_tf
        - RECSYS_LIST= 
        - RANKSYS_PRECOM_LIST=pyterrier_tf
        - RECSYS_PRECOM_LIST= 
        - RANKSYS_BASE=pyterrier_bm25
        - RECSYS_BASE=
        - STELLA_SERVER_ADDRESS=http://web:8000
        - STELLA_SERVER_USER=livivo@stella-project.org
        - STELLA_SERVER_PASS=pass
        - STELLA_SERVER_USERNAME=LIVIVO
        - INTERLEAVE=True
        - BULK_INDEX=True
        - DELETE_SENT_SESSION=False
        - INTERVAL_DB_CHECK=3
        - SESSION_EXPIRATION=240
  db:
    image: postgres
    ports:
        - 5432:5432
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres

  pyterrier_bm25:
    build: https://github.com/stella-project/stella-micro-pyterrier.git#master
    container_name: pyterrier_bm25
    volumes:
      - ../index/:/index/
    environment:
      - WMODEL=BM25

  pyterrier_pl2:
    build: https://github.com/stella-project/stella-micro-pyterrier.git#master
    container_name: pyterrier_pl2
    volumes:
      - ../index/:/index/
    environment:
      - WMODEL=PL2

  pyterrier_tf:
    build: https://github.com/stella-project/stella-micro-pyterrier.git#master
    container_name: pyterrier_tf
    volumes:
      - ../index/:/index/
    environment:
      - WMODEL=Tf

  web:
    restart: always
    build: https://github.com/stella-project/stella-server.git#pyterrier:web
    ports:
      - 8040:8000
    command: bash -c "python stella-server.py"
    environment:
      - FLASK_CONFIG=demo
      - POSTGRES_USER=postgres
      - POSTGRES_PW=postgres
      - POSTGRES_DB=postgres
      - SECRET_KEY=change-me
      - AUTOMATOR_GH_KEY=
      - ADMIN_MAIL=admin@stella-project.org
      - ADMIN_PASS=pass
      - GESIS_MAIL=gesis@stella-project.org
      - GESIS_PASS=pass
      - LIVIVO_MAIL=livivo@stella-project.org
      - LIVIVO_PASS=pass
      - PARTA_MAIL=participant_a@stella-project.org
      - PARTA_PASS=pass
      - PARTB_MAIL=participant_b@stella-project.org
      - PARTB_PASS=pass
    depends_on:
      - db_server

  db_server:
    image: postgres
    expose:
      - 5430
    ports:
      - 5430:5430
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    command: -p 5430